const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
(async () => {
  const art = fs.readFileSync(path.join(__dirname, '..', 'dist', 'artifact.html'), 'utf8');
  const doc = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light;padding-top:env(safe-area-inset-top);padding-bottom:env(safe-area-inset-bottom)}body{margin:0;font:14px system-ui;background:#fafafa}img{max-width:100%}[hidden]{display:none!important}</style></head><body>${art}</body></html>`;
  const outer = `<!doctype html><html><body style="margin:0"><iframe id="f" sandbox="allow-scripts" style="border:0;width:390px;height:844px"></iframe><script>document.getElementById("f").srcdoc = ${JSON.stringify(doc).replace(/<\//g, "<\\/")};</script></body></html>`;
  fs.writeFileSync(path.join(__dirname, 'frame.html'), outer);
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = [];
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('file://' + path.join(__dirname, 'frame.html'));
  await page.waitForTimeout(800);
  const frame = page.frames().find(f => f !== page.mainFrame());
  const homeRows = await frame.evaluate(() => document.querySelectorAll('#v-home .row').length);
  await frame.click('.carousel .dcard');
  await frame.waitForTimeout(300);
  const sheet = await frame.evaluate(() => !!document.querySelector('.panel h2'));
  await frame.click('.panel [data-act="fav"]');
  await frame.click('.panel [data-act="close"]');
  await frame.evaluate(() => document.querySelector('.tabs [data-go="quiz"]').click());
  for (const [q, k] of [['mood', 'tired'], ['where', 'post'], ['flavor', 'coffee'], ['strength', '1'], ['spirit', 'any']]) await frame.click(`[data-act="answer"][data-q="${q}"][data-k="${k}"]`);
  const match = await frame.textContent('.match h2');
  const status = await frame.textContent('#status span');
  await page.screenshot({ path: path.join(__dirname, 'shots', '30-sandbox.png') });
  console.log(JSON.stringify({ homeRows, sheet, match, status, errors }, null, 1));
  await browser.close();
})();
